### ISSUE TITLE
Feature Request: Mempool cache of all the seen transactions

### ISSUE THREAD

**Issue by charithabandi** [kwilteam/kwil-db#1142]
### Describe the Feature

@jchappelow  How about having a cache for all the previously seen transactions to remove duplicates. This includes the transactions that failed checkTx. This might be a way to go to fix this issue

```
// store in mempool since it was not in tx index and thus not confirmed
	ctx := context.Background()
	if err := n.ce.CheckTx(ctx, rawTx); err != nil {
		n.log.Warnf("tx %v failed check: %v", txHash, err)
	} else {
		n.mp.Store(txHash, rawTx)

		// re-announce
		go n.announceTx(context.Background(), txHash, rawTx, s.Conn().RemotePeer())
```

**Comment by jchappelow** [comment]
Meaning previously seen but rejected?  Or previously seen and no longer in mempool because it was mined?  For the former, we discussed issues about txns not being perpetually invalid, especially in an asynchronous gossip environment and/or with network interruptions.  For the latter (mined), we have the tx ann stream handler checking txindex for that, but it could be improved with a smaller, faster in-memory index (see comment in store.go about a possible LRU cache for that)
